"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.2.8.
"""

from pathlib import Path
import os,dj_database_url
from dotenv import load_dotenv


# --------------------------------------
# BASE CONFIG
# --------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-w-dgp@dc+pkti&t*9mtcy)y&#-%6rqf%g22^h%3x-&ru7q@so9'
DEBUG = True
ALLOWED_HOSTS = ['*']
load_dotenv()
# --------------------------------------
# INSTALLED APPS
# --------------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'backend',       # your app
    'storages',        # required for S3
]

# --------------------------------------
# MIDDLEWARE
# --------------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'giftart.urls'

# --------------------------------------
# TEMPLATES
# --------------------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # optional
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'giftart.wsgi.application'
# --------------------------------------
# DATABASE
# --------------------------------------
DATABASES = {
        'default': dj_database_url.parse(os.environ.get('DATABASE_URL'))
    }

# --------------------------------------
# PASSWORD VALIDATION
# --------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# --------------------------------------
# INTERNATIONALIZATION
# --------------------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# --------------------------------------
# STATIC & MEDIA
# --------------------------------------
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR/'static']

# Disable local media folder (we use S3 instead)
MEDIA_ROOT = ''
MEDIA_URL = ''

# --------------------------------------
# AWS S3 STORAGE CONFIGURATION
# --------------------------------------

AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = "sachuqari"
AWS_S3_REGION_NAME = "eu-north-1"
AWS_S3_SIGNATURE_VERSION = "s3v4"

# Public-read files, cleaner URLs
AWS_DEFAULT_ACL = None
AWS_S3_FILE_OVERWRITE = True
AWS_QUERYSTRING_AUTH = False
AWS_S3_CUSTOM_DOMAIN = f"{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com"

# --------------------------------------
# DJANGO-STORAGES CONFIG (Django 5.x)
# --------------------------------------
DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"

STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# --------------------------------------
# DEFAULT PRIMARY KEY FIELD TYPE
# --------------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'